Repository Team-GAJI/GAJI-Front-v1.0, pull requests merged in 2024-08, with the labels that each got.

#42 [FEATURE] 트러블슈팅게시판글등록레이아웃
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/components/StudyCategory/BackStudyRecruitment.jsx
  src/assets/components/StudyCategory/DetailCategory.jsx
  src/assets/components/StudyCategory/FilterCategory.jsx
  src/assets/components/StudyCategory/FlippingCard.jsx
  src/assets/components/StudyCategory/SortingCategory.jsx
  src/assets/components/StudyCategory/StudyCategory.jsx
  src/assets/components/StudyCategory/StudyRecruitment.jsx
  src/assets/components/TroubleShooting/Category.jsx
  src/assets/components/TroubleShooting/ItemList.jsx
  src/assets/components/TroubleShooting/TitleSection.jsx
  src/assets/components/TroubleShooting/TroubleShootingPage.jsx
  src/assets/icons/usericon.svg
  src/assets/images/example.png
  src/assets/images/titleBackground.png
  src/assets/images/troubleshooting/titleBackground.png
  src/components/troubleshooting/AddedPostPrieview.jsx
  src/main.jsx
  src/pages/CommunityPostPage.jsx
  src/pages/TroubleShootingPage.jsx
  src/pages/TroubleshootingRegistrationPage.jsx
  src/store/anotherReducer.jsx
  src/store/rootReducer.jsx
  src/store/someReducer.jsx
  src/store/store.jsx
Labels: ✨ Feature

#44 [CHORE] 3주차 병합
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/components/StudyCategory/BackStudyRecruitment.jsx
  src/assets/components/StudyCategory/DetailCategory.jsx
  src/assets/components/StudyCategory/FilterCategory.jsx
  src/assets/components/StudyCategory/FlippingCard.jsx
  src/assets/components/StudyCategory/SortingCategory.jsx
  src/assets/components/StudyCategory/StudyCategory.jsx
  src/assets/components/StudyCategory/StudyRecruitment.jsx
  src/assets/components/TroubleShooting/TroubleShootingPage.jsx
  src/assets/icons/common/Arrow.png
  src/assets/icons/common/BookMark.png
  src/assets/icons/common/Caution.png
  src/assets/icons/common/Heart.png
  src/assets/icons/common/Plus.png
  src/assets/icons/common/Vector.png
  src/assets/icons/common/bellicon.svg
  src/assets/icons/common/plusicon.svg
  src/assets/icons/common/sendicon.svg
  src/assets/icons/common/usericon.svg
  src/assets/images/common/Rectangle16.png
  src/assets/images/common/example.png
  src/assets/images/common/mypageBackground.png
  src/assets/images/common/studyprofile.png
  src/assets/images/common/titleBackground.png
  src/assets/images/studyCategory/Rectangle16.png
  src/components/StudyCategory/BackStudyRecruitment.jsx
  src/components/StudyCategory/FlippingCard.jsx
  src/components/StudyManage/StudyManageCalendar.jsx
  src/components/communityWrite/WritePost.jsx
  src/components/mypage/MyPost.jsx
  src/components/mypage/StudyList.jsx
  src/components/troubleshooting/Category.jsx
  src/components/troubleshooting/ItemList.jsx
  src/components/troubleshooting/TitleSection.jsx
  src/main.jsx
  src/pages/Footer.jsx
  src/pages/StudyCategoryPage.jsx
  src/pages/StudyCreatePage.jsx
  src/pages/StudyManagePage.jsx
  src/pages/StudyNoticePage.jsx
  src/pages/StudyPage.jsx
  src/pages/StudyRoomPage.jsx
  src/pages/TroubleShootingPage.jsx
Labels: ⚙ Setting

#45 [FEATURE] PageHeader.jsx 공용 컴포넌트 작성
  src/App.jsx
  src/assets/icons/common/menuBar.svg
  src/components/common/Header.jsx
  src/components/common/PageHeader.jsx
  src/pages/MyPage.jsx
  src/pages/StudyCategoryPage.jsx
  src/pages/StudyManagePage.jsx
  src/pages/StudyRoomPage.jsx
  src/store/anotherSlice.jsx
  src/store/rootReducer.jsx
  src/store/someSlice.jsx
  src/store/store.jsx
  src/utils/API.jsx
Labels: ✨ Feature

#51 [FEATURE] 커뮤니티 관련 레이아웃 수정 및 기능 구현
  src/components/common/Header.jsx
  src/components/common/PageHeader.jsx
  src/components/community/BlogPreview.jsx
  src/components/community/CommunityHomePosts.jsx
  src/components/community/ProjectPreview.jsx
  src/components/community/QuestionPreview.jsx
  src/components/communityPost/Comment.jsx
  src/components/communityPost/CommentContainer.jsx
  src/components/communityPost/DummyComments.jsx
  src/components/communityWrite/Hashtag.jsx
  src/components/communityWrite/WritePost.jsx
  src/layout/MainLayOut.jsx
  src/pages/CommunityPage.jsx
  src/pages/CommunityPostPage.jsx
  src/pages/CommunityWritePage.jsx
Labels: ✨ Feature

#52 [FEATURE] 홈화면 레이아웃 및 기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/communityPost/downArrow2.svg
  src/assets/images/.DS_Store
  src/assets/images/community/blogBackground.png
  src/assets/images/community/postBackground.png
  src/components/community/BlogPreview.jsx
  src/components/community/CommunityHomePosts.jsx
  src/components/community/DummyBlogPosts.jsx
  src/components/community/DummyHotPosts.jsx
  src/components/community/HotPostPreview.jsx
  src/components/community/SelectBox.jsx
  src/components/main/DummyStudyPosts.jsx
  src/components/main/StudyPreview.jsx
  src/pages/CommunityPage.jsx
  src/pages/CommunityPostPage.jsx
  src/pages/CommunityWritePage.jsx
  src/pages/MainPage.jsx
Labels: ✨ Feature

#54 [FEATURE] 스터디룸 기능 구현
  src/App.jsx
  src/assets/icons/createStudy/CreateStudyDelete.png
  src/assets/icons/createStudy/CreateStudynextmonth.svg
  src/assets/icons/createStudy/CreateStudyprevmonth.svg
  src/assets/icons/noticeRoom/NoticeAlarm.png
  src/assets/icons/noticeRoom/NoticePlus.png
  src/assets/icons/studyCategory/CategoryArrow.png
  src/assets/icons/studyCategory/CategoryVector.png
  src/assets/icons/studyCategory/Categoryplusicon.png
  src/assets/icons/studyManage/StudyManageDel.png
  src/assets/icons/studyManage/StudyManageDelete.png
  src/assets/icons/studyManage/StudyManagePlus.png
  src/assets/icons/studyManage/StudyManagePlus.svg
  src/assets/icons/studyManage/StudyManagenextmonth.svg
  src/assets/icons/studyManage/StudyManageprevmonth.svg
  src/assets/icons/studyRoom/Alarm.png
  src/assets/icons/studyRoom/Plus.png
  src/assets/images/studyRoom/Rectangle 34624913.png
  src/components/common/PageHeader.jsx
  src/components/createStudy/CreateBasics.jsx
  src/components/createStudy/CreateCalendar.jsx
  src/components/createStudy/CreateDate.jsx
  src/components/createStudy/CreateDetailed.jsx
  src/components/createStudy/CreateWrithePost.jsx
  src/components/studyCategory/BackStudyRecruitment.jsx
  src/components/studyCategory/DetailCategory.jsx
  src/components/studyCategory/FilterCategory.jsx
  src/components/studyCategory/FlippingCard.jsx
  src/components/studyCategory/SortingCategory.jsx
  src/components/studyCategory/StudyRecruitment.jsx
  src/components/studyManage/ManageBasics.jsx
  src/components/studyManage/ManageDate.jsx
  src/components/studyManage/ManageDetailed.jsx
  src/components/studyManage/ManageWrithePost.jsx
  src/components/studyManage/StudyManageCalendar.jsx
  src/components/studyRoom/StudyPostList.jsx
  src/components/studyRoom/StudyRecruitment.jsx
  src/components/studyRoom/StudySummary.jsx
  src/components/studyRoom/WeekCurriculum.jsx
  src/pages/MyPage.jsx
  src/pages/StudyRoomPage.jsx
Labels: ✨ Feature, 🎨 Html&css

#60 [FEATURE] page header수정및app.jsx수정
  src/App.jsx
  src/components/common/PageHeader.jsx
  src/components/community/CommunityHomePosts.jsx
  src/components/mypage/MyPageHeader.jsx
  src/pages/MyPage.jsx
Labels: ✨ Feature, 🎨 Html&css

#70 [ FEATURE ] 스터디 관리 페이지 수정 및 API
  src/App.jsx
  src/components/studyManage/ManageBasics.jsx
  src/components/studyManage/ManageDate.jsx
  src/components/studyManage/ManageDetailed.jsx
  src/pages/StudyManagePage.jsx
Labels: ✨ Feature

#72 [FEATURE] apiInstance 생성
  src/utils/auth/googleLogin.jsx
Labels: ✨ Feature, 📬 API

#73 [FEATURE] 스터디 모집 관련 기능 및 레이아웃 구현
  src/assets/icons/studyDetail/reportCheck.svg
  src/assets/images/mainPage/banner1.png
  src/assets/images/mainPage/banner2.png
  src/assets/images/mainPage/banner3.png
  src/components/communityWrite/WritePost.jsx
  src/components/createStudy/CreateBasics.jsx
  src/components/createStudy/CreateCalendar.jsx
  src/components/createStudy/CreateDate.jsx
  src/components/createStudy/CreateDetailed.jsx
  src/components/createStudy/CreateWrithePost.jsx
  src/components/studyCreate/StudyCreateLinkEmbed.jsx
  src/components/studyCreate/StudyData.jsx
  src/components/studyCreate/StudyDetail.jsx
  src/components/studyCreate/StudyInfo.jsx
  src/components/studyDetail/ReportModal.jsx
  src/components/studyDetail/StudyDetailHeader.jsx
  src/pages/CommunityPostPage.jsx
  src/pages/MainPage.jsx
  src/pages/StudyCreatePage.jsx
  src/pages/StudyMainPage.jsx
Labels: ✨ Feature

#77 [FEATURE] 메인페이지 반응형 구현 및 Scroll.jsx 구현, Header.jsx 수정
  src/App.jsx
  src/components/common/Header.jsx
  src/components/common/MediaWrapper.jsx
  src/components/common/Scroll.jsx
  src/components/main/MainSelectBox.jsx
  src/components/studyMain/StudyPreview.jsx
  src/components/studyRoom/WeekCurriculum.jsx
  src/feautres/auth/authSlice.jsx
  src/pages/LoginPage.jsx
  src/pages/LoginRedirectPage.jsx
  src/pages/MainPage.jsx
  src/pages/StudyCreatePage.jsx
  src/pages/StudyRoomPage.jsx
  src/store/store.jsx
  src/utils/API.jsx
  src/utils/mypage/studyInfoAPI.jsx
  src/utils/studyRoom/studyManageInfo.jsx
Labels: ✨ Feature, 🎨 Html&css

#82 [CSS] 작성, 스터디, 커뮤니티 페이지 반응형 구현 완료
  src/assets/images/common/studyExampleImage.png
  src/components/common/Header.jsx
  src/components/common/MediaWrapper.jsx
  src/components/common/PageHeader.jsx
  src/components/community/BlogPreview.jsx
  src/components/community/CommunityHomePosts.jsx
  src/components/community/CommunitySelectBox.jsx
  src/components/communityWrite/Hashtag.jsx
  src/components/communityWrite/WritePost.jsx
  src/components/communityWrite/WriteSelectBox.jsx
  src/components/main/MainSelectBox.jsx
  src/components/studyMain/DummyStudyPosts.jsx
  src/index.css
  src/pages/CommunityPage.jsx
  src/pages/CommunityWritePage.jsx
  src/pages/MainPage.jsx
  src/pages/StudyCreatePage.jsx
  src/pages/StudyMainPage.jsx
  src/pages/StudyManagePage.jsx
Labels: 🎨 Html&css

#83 [BUG] bug수정
  src/pages/StudyManagePage.jsx
Labels: 🐞 BugFix

#84 [API] 네이버 로그인 /api/ 제거
  src/pages/LoginPage.jsx
Labels: 🐞 BugFix, 📬 API

#85 [API] 스터디모집 API 연결
  src/components/communityWrite/WritePost.jsx
  src/components/studyCreate/StudyCreateCalendar.jsx
  src/components/studyCreate/StudyCreateRecruitCalendar.jsx
  src/components/studyCreate/StudyCreateSelectBox.jsx
  src/components/studyCreate/StudyDetail.jsx
  src/components/studyCreate/StudyInfo.jsx
  src/components/studyCreate/StudyPeriod.jsx
  src/feautres/study/studyCreateSlice.jsx
  src/pages/StudyCreatePage.jsx
  src/store/store.jsx
Labels: 📬 API

#89 [FEATURE] WirtePost수정
  src/App.jsx
  src/components/common/WritePost.jsx
  src/components/troubleshooting/WritePost.jsx
  src/pages/CommunityWritePage.jsx
  src/pages/LoginPage.jsx
  src/pages/StudyManageWeekPage.jsx
  src/pages/TroubleshootingRegistrationPage.jsx
  src/utils/troubleShooting/troubleShootingInfoAPI.jsx
Labels: ✨ Feature

#90 [FEATURE] 스터디모집 API 연결
  src/assets/images/common/communityExampleImage.png
  src/components/community/DummyBlogPosts.jsx
  src/components/community/DummyHotPosts.jsx
Labels: ✨ Feature, 📬 API

#93 [BUG] 깃 관련 에러 핸들링
  src/assets/images/troubleshooting/ troubleComment.png
  src/components/troubleshooting/Category.jsx
  src/components/troubleshooting/Comment.jsx
  src/components/troubleshooting/CommentContainer.jsx
  src/components/troubleshooting/DummyComments.jsx
  src/components/troubleshooting/ItemList.jsx
  src/components/troubleshooting/PostWriterInfo.jsx
  src/components/troubleshooting/ReportModal.jsx
  src/pages/MyPage.jsx
  src/pages/TroubleshootingDetailPage.jsx
  src/utils/mypage/myInfoAPI.jsx
  src/utils/mypage/myStudyListAPI.jsx
  src/utils/studyRoom/studyInfoAPI.jsx
Labels: 🐞 BugFix

#95 [BUG] myInfoAPI 수정
  src/utils/mypage/myInfoAPI.jsx
Labels: 🐞 BugFix

#98 [API] 커뮤니티 API 연결
  src/feautres/community/communityWriteSlice.jsx
  src/store/store.jsx
  src/utils/communityWrite/communityWriteAPI.jsx
  src/utils/studyCreate/studyCreateAPI.jsx
Labels: 📬 API

#97 [API] 마이페이지api
  src/components/common/WritePost.jsx
  src/components/communityWrite/WriteSelectBox.jsx
  src/components/mypage/StudyList.jsx
  src/components/mypage/UserInfo.jsx
  src/components/studyCreate/StudyCreateSelectBox.jsx
  src/components/studyCreate/StudyData.jsx
  src/components/studyCreate/StudyDetail.jsx
  src/components/studyCreate/StudyInfo.jsx
  src/components/studyCreate/StudyPeriod.jsx
  src/features/community/communitySlice.jsx
  src/features/posts/commentSlice.jsx
  src/features/posts/postSlice.jsx
  src/features/study/studyCreateSlice.jsx
  src/pages/CommunityPage.jsx
  src/pages/CommunityWritePage.jsx
  src/pages/LoginRedirectPage.jsx
  src/pages/MyPage.jsx
  src/store/anotherSlice.jsx
  src/store/someSlice.jsx
  src/utils/API.jsx
  src/utils/mypage/myInfoAPI.jsx
  src/utils/mypage/myStudyListAPI.jsx
  src/utils/mypage/studyInfoAPI.jsx
  src/utils/mypage/userInfoAPI.jsx
  src/utils/studyRoom/studyInfoAPI.jsx
  src/utils/troubleShooting/troubleShootingInfoAPI.jsx
Labels: 🐞 BugFix, 📬 API

#99 [BUG] featrues -> features
  src/components/studyManage/StudyManagePeriod.jsx
  src/features/community/communityWriteSlice.jsx
  src/store/store.jsx
Labels: 🐞 BugFix

#100 [CSS] 모든 페이지 반응형 구현
  src/components/common/Header.jsx
  src/components/common/MediaWrapper.jsx
  src/components/common/SidePageHeader.jsx
  src/components/common/WritePost.jsx
  src/components/communityPost/Comment.jsx
  src/components/communityPost/CommentContainer.jsx
  src/components/communityWrite/WriteSelectBox.jsx
  src/components/mypage/StudyList.jsx
  src/components/studyCreate/StudyCreateCalendar.jsx
  src/components/studyCreate/StudyCreateRecruitCalendar.jsx
  src/components/studyCreate/StudyCreateSelectBox.jsx
  src/components/studyCreate/StudyData.jsx
  src/components/studyCreate/StudyDetail.jsx
  src/components/studyCreate/StudyInfo.jsx
  src/components/studyCreate/StudyPeriod.jsx
  src/components/studyManage/LinkData.jsx
  src/components/studyManage/LinkEmbed.jsx
  src/components/studyManage/ManageDetailed.jsx
  src/components/studyManage/ManageInfo.jsx
  src/components/studyManage/StudyManageCalendar.jsx
  src/components/studyManage/StudyManageDetail.jsx
  src/components/studyManage/StudyManagePeriod.jsx
  src/components/studyManage/StudyManageRecruitCalendar.jsx
  src/components/studyManageWeek/ManageWeekBasics.jsx
  src/components/studyManageWeek/ManageWeekCalendar.jsx
  src/components/studyManageWeek/ManageWeekDate.jsx
  src/components/studyManageWeek/ManageWeekDetailed.jsx
  src/components/studyManageWeek/StudyManageWeekCalendar.jsx
  src/components/studyManageWeek/StudyManageWeekRecruitCalendar.jsx
  src/components/studyManageWeek/StudyMangeWeekPeriod.jsx
  src/components/studyRoom/FirstNoticeSquare.jsx
  src/components/studyRoom/NoticeSquare.jsx
  src/components/studyRoom/Notices.jsx
  src/components/troubleshooting/Category.jsx
  src/pages/CommunityPostPage.jsx
  src/pages/CommunityWritePage.jsx
  src/pages/MyPage.jsx
  src/pages/StudyCreatePage.jsx
  src/pages/StudyManagePage.jsx
  src/pages/StudyManageWeekPage.jsx
  src/pages/StudyNoticePage.jsx
  src/pages/StudyNoticeRegistrationPage.jsx
  src/pages/TroubleShootingPage.jsx
  src/pages/TroubleshootingRegistrationPage.jsx
Labels: 🎨 Html&css

#101 [BUG] troubleComment 이미지 이름 공백 수정
  src/assets/images/troubleshooting/troubleComment.png
Labels: 🐞 BugFix

#102 [API] API.jsx 수정 및 userIdAPI 성공
  src/components/common/Header.jsx
  src/pages/LoginPage.jsx
  src/pages/LoginRedirectPage.jsx
  src/utils/auth/nickNameAPI.jsx
  src/utils/auth/userIdAPI.jsx
Labels: 📬 API

#104 [API] 스터디 생성, 스터디 상세 조회 API
  src/components/mypage/StudyList.jsx
  src/components/mypage/UserInfo.jsx
  src/components/studyCreate/StudyDetail.jsx
  src/components/studyDetail/StudyDetailHeader.jsx
  src/pages/LoginRedirectPage.jsx
  src/pages/MyPage.jsx
  src/pages/StudyCreatePage.jsx
  src/pages/StudyDetailPage.jsx
  src/utils/API.jsx
  src/utils/auth/nickNameAPI.jsx
  src/utils/auth/userIdAPI.jsx
  src/utils/mypage/myStudyListAPI.jsx
  src/utils/mypage/studyInfoAPI.jsx
  src/utils/mypage/userInfoAPI.jsx
  src/utils/studyCreate/studyCreateAPI.jsx
  src/utils/studyDetail/studyDetailAPI.jsx
  src/utils/studyManage/studyManageDateAPI.jsx
  src/utils/studyManageWeek/descriptionAPI.jsx
  src/utils/troubleShooting/troubleShootingInfoAPI.jsx
Labels: 📬 API

#105 [API] 커뮤니티 작성 API 연결
  src/components/common/CommunityWritePost.jsx
  src/components/community/CommunityHomePosts.jsx
  src/components/communityWrite/WriteSelectBox.jsx
  src/components/studyCreate/StudyCreateSelectBox.jsx
  src/features/community/communitySlice.jsx
  src/features/community/communityWriteSlice.jsx
  src/features/study/studyCreateSlice.jsx
  src/pages/CommunityWritePage.jsx
  src/pages/StudyCreatePage.jsx
  src/utils/communityWrite/communityWriteAPI.jsx
  src/utils/studyCreate/studyCreateAPI.jsx
Labels: 📬 API

#106 [BUG] Git 오류 수정
  src/components/common/CommunityWritePost.jsx
  src/pages/CommunityWritePage.jsx
  src/pages/MyPage.jsx
  src/utils/mypage/myStudyListAPI.jsx
  src/utils/studyCreate/studyCreateAPI.jsx
Labels: 🐞 BugFix

#107 [API] 마이페이지->스터디룸 API
  src/components/mypage/StudyList.jsx
  src/components/studyRoom/StudySummary.jsx
  src/components/studyRoom/WeekCurriculum.jsx
  src/pages/MyPage.jsx
  src/pages/StudyCreatePage.jsx
  src/pages/StudyRoomPage.jsx
  src/utils/mypage/studyInfoAPI.jsx
  src/utils/studyCreate/studyCreateAPI.jsx
Labels: 📬 API

#108 [BUG[ studyCreateAPI 수정
  src/components/common/CommunityWritePost.jsx
  src/components/common/WritePost.jsx
  src/components/studyCreate/StudyCreateSelectBox.jsx
  src/components/studyCreate/StudyInfo.jsx
  src/pages/TroubleshootingDetailPage.jsx
  src/pages/TroubleshootingRegistrationPage.jsx
  src/utils/communityWrite/communityWriteAPI.jsx
Labels: 🐞 BugFix, 📬 API

#109 [CSS] 스터디디테일페이지 반응형
  src/components/studyDetail/ReportModal.jsx
  src/components/studyDetail/StudyComment.jsx
  src/components/studyDetail/StudyCommentContainer.jsx
  src/components/studyDetail/StudyDetailHeader.jsx
  src/components/studyDetail/StudyPostWriterInfo.jsx
  src/pages/StudyCreatePage.jsx
  src/pages/StudyDetailPage.jsx
Labels: 🎨 Html&css

#110 [FEATURE] 스터디 모집 기능 수정
  src/components/common/CommunityWritePost.jsx
  src/components/common/PageHeader.jsx
  src/components/studyCreate/StudyCreateCalendar.jsx
  src/components/studyCreate/StudyCreateRecruitCalendar.jsx
  src/components/studyCreate/StudyInfo.jsx
  src/components/studyCreate/StudyPeriod.jsx
  src/pages/StudyDetailPage.jsx
  src/utils/studyPreview/studyPreviewAPI.jsx
Labels: ✨ Feature

#111 [CSS] 메이펜이지 커뮤니티 페이지 , StudyPreview, BlogPreview 반응형
  package.json
  src/assets/icons/common/writeIcon.svg
  src/components/common/Header.jsx
  src/components/common/MobileWriteButton.jsx
  src/components/community/BlogPreview.jsx
  src/components/community/CommunityHomePosts.jsx
  src/components/studyMain/StudyPreview.jsx
  src/pages/CommunityPostPage.jsx
  src/pages/MainPage.jsx
  src/pages/StudyCategoryPage.jsx
  src/pages/StudyMainPage.jsx
Labels: 🎨 Html&css

#112 [CSS] 스터디룸 주차별 정보 헤더 반응형 수정
  src/assets/icons/common/studyManageIcon.svg
  src/assets/images/common/userProfile.png
  src/assets/images/community/userProfile.png
  src/components/common/MobileManageButton.jsx
  src/components/community/CommunityHomePosts.jsx
  src/components/studyDetail/StudyPostWriterInfo.jsx
  src/pages/StudyCategoryPage.jsx
  src/pages/StudyDetailPage.jsx
  src/pages/StudyManagePage.jsx
  src/pages/StudyRoomPage.jsx
Labels: 🎨 Html&css

#113 [API] 스터디 메인, 스터디 카테고리, 스터디 상세보기 API 연결
  src/components/community/CommunitySelectBox.jsx
  src/components/communityWrite/WriteSelectBox.jsx
  src/components/main/MainSelectBox.jsx
  src/components/studyCreate/StudyCreateSelectBox.jsx
  src/components/studyDetail/StudyLinkEmbed.jsx
  src/components/studyMain/StudyPreview.jsx
  src/pages/MainPage.jsx
  src/pages/StudyCategoryPage.jsx
  src/pages/StudyDetailPage.jsx
  src/pages/StudyMainPage.jsx
  src/utils/studyMain/studyPostsPreviewAPI.jsx
  src/utils/studyPreview/studyPreviewAPI.jsx
Labels: 📬 API

#116 [FEATURE] 스터디 관리 페이지 -> 주차별 관리페이지 roomId전달
  src/pages/StudyMainPage.jsx
  src/pages/StudyManagePage.jsx
  src/pages/StudyManageWeekPage.jsx
Labels: ✨ Feature

#118 [FEATURE] 스터디룸 기능
  src/components/studyRoom/StudySummary.jsx
  src/pages/StudyNoticePage.jsx
  src/pages/StudyNoticeRegistrationPage.jsx
  src/pages/StudyRoomPage.jsx
  src/utils/studyRoom/studyNoticeAPI.jsx
  src/utils/studyRoom/studyNoticeRegisterAPI.jsx
Labels: ✨ Feature, 📬 API

#119 [API] 커뮤니티 메인 API 연결
  src/App.jsx
  src/components/common/CommunityWritePost.jsx
  src/components/community/BlogPreview.jsx
  src/components/community/CommunityHomePosts.jsx
  src/components/community/CommunitySelectBox.jsx
  src/components/community/ProjectPreview.jsx
  src/components/community/QuestionPreview.jsx
  src/components/communityPost/PostWriterInfo.jsx
  src/components/communityWrite/WriteSelectBox.jsx
  src/components/main/MainSelectBox.jsx
  src/components/studyCreate/StudyCreateSelectBox.jsx
  src/components/studyDetail/StudyDetailHeader.jsx
  src/components/studyDetail/StudyPostWriterInfo.jsx
  src/features/community/communityWriteSlice.jsx
  src/pages/CommunityPostPage.jsx
  src/pages/StudyCategoryPage.jsx
  src/pages/StudyDetailPage.jsx
  src/pages/StudyMainPage.jsx
  src/utils/communityMain/communityPostsPreviewAPI.jsx
  src/utils/communityPost/commuityPostAPI.jsx
  src/utils/communityWrite/communityWriteAPI.jsx
Labels: 📬 API

#122 [API] 커뮤니티 핫 게시물 API 연결
  src/components/common/CommunityWritePost.jsx
  src/components/community/BlogPreview copy.jsx
  src/components/community/BlogPreview.jsx
  src/components/community/CommunityHomePosts.jsx
  src/components/community/HotPostPreview.jsx
  src/components/community/ProjectPreview.jsx
  src/components/community/QuestionPreview.jsx
  src/components/studyMain/StudyPreview.jsx
  src/pages/CommunityPage.jsx
  src/utils/communityPost/communityPostAPI.jsx
Labels: 📬 API

#123 [API] 홈화면 커뮤니티 미리보기 API 구현
  src/components/community/BlogPreview.jsx
  src/components/community/HotPostPreview.jsx
  src/pages/CommunityPage.jsx
  src/pages/MainPage.jsx
Labels: 📬 API

#124 [BUG] 오류 핸들링
  src/components/studyRoom/WeekCurriculum.jsx
Labels: 🐞 BugFix

#125 [API] 커뮤니티 셀렉트박스 구현
  src/components/community/CommunityHomePosts.jsx
  src/components/community/CommunitySelectBox.jsx
  src/components/community/HotPostPreview.jsx
  src/pages/CommunityPage.jsx
  src/utils/communityMain/communityPostsPreviewAPI.jsx
Labels: 📬 API

#126 [API] 스터디 가지기 API 연결
  src/components/community/CommunityHomePosts.jsx
  src/components/main/MainSelectBox.jsx
  src/components/studyDetail/StudyDetailHeader.jsx
  src/components/studyMain/StudyPreview.jsx
  src/pages/StudyCategoryPage.jsx
  src/pages/StudyCreatePage.jsx
  src/pages/StudyDetailPage.jsx
  src/pages/StudyMainPage.jsx
  src/utils/studyDetail/studyRecruitAPI.jsx
Labels: 📬 API

#127 [FEATURE] 스터디 가지기 성공 시 마이페이지로 이동 구현
  src/components/studyDetail/StudyDetailHeader.jsx
Labels: ✨ Feature

#129 [API] 스터디 댓글 API 연결
  src/components/studyDetail/StudyComment.jsx
  src/components/studyDetail/StudyCommentContainer.jsx
  src/pages/StudyDetailPage.jsx
  src/utils/studyDetail/studyCommentAPI.jsx
Labels: 📬 API

#130 [FEATURE]
  src/App.jsx
  src/components/community/BlogPreview.jsx
  src/components/mypage/StudyList.jsx
  src/components/studyDetail/StudyDetailHeader.jsx
  src/components/studyRoom/StudyPostList.jsx
  src/components/studyRoom/StudyRoomWritePost.jsx
  src/components/studyRoom/WeekCurriculum.jsx
  src/pages/LoginPage.jsx
  src/pages/StudyRoomPage.jsx
  src/pages/StudyRoomPostPage.jsx
  src/pages/StudyRoomWritePage.jsx
  src/pages/TroubleShootingPage.jsx
  src/utils/communityPost/commuityPostAPI.jsx
  src/utils/studyRoom/studyRoomPostDetailAPI.jsx
  src/utils/studyRoom/studyRoomPostPreviewAPI.jsx
  src/utils/studyRoom/studyRoomWriteAPI.jsx
  src/utils/studyRoom/weekStudyInfoAPI.jsx
  src/utils/studyRoom/weekTaskProgressAPI.jsx
Labels: ✨ Feature

#132 [API] 커뮤니티 댓글 API 연결
  src/components/common/CommunityWritePost.jsx
  src/components/studyDetail/StudyCommentContainer.jsx
  src/pages/CommunityPostPage.jsx
  src/pages/StudyDetailPage.jsx
  src/utils/auth/commentAPI.jsx
  src/utils/studyDetail/studyCommentAPI.jsx
Labels: 📬 API

#139 [BUG] 스터디 디테일 버그 수정
  index.html
  src/components/studyDetail/StudyDetailHeader.jsx
Labels: 🐞 BugFix

#143 [FEATURE] 스터디룸 일부 수정
  src/components/studyRoom/WeekCurriculum.jsx
Labels: ✨ Feature
